import type { Prisma, PromptProfile } from "@prisma/client"
import { prisma } from "./client"

export const promptProfileService = {
  /**
   * Create a prompt profile
   * Note: Type casting to Prisma.InputJsonValue is required due to
   * known Prisma type incompatibility with JSON fields
   */
  async create(data: {
    name: string
    summaryPrompt: string
    llmsTxtHeader?: string
    assembleTemplate?: string
    params?: Record<string, unknown>
    version?: number
  }): Promise<PromptProfile> {
    return prisma.promptProfile.create({
      data: {
        name: data.name,
        summary_prompt: data.summaryPrompt,
        llms_txt_header: data.llmsTxtHeader,
        assemble_template: data.assembleTemplate,
        params: (data.params ?? {}) as Prisma.InputJsonValue,
        version: data.version ?? 1,
      },
    })
  },

  /**
   * Get prompt profile by ID
   */
  async getById(id: string): Promise<PromptProfile | null> {
    return prisma.promptProfile.findUnique({
      where: { id },
      include: {
        domains: true,
      },
    })
  },

  /**
   * Get all prompt profiles
   */
  async getAll(): Promise<PromptProfile[]> {
    return prisma.promptProfile.findMany({
      orderBy: [{ version: "desc" }, { created_at: "desc" }],
    })
  },

  /**
   * Update prompt profile
   */
  async update(
    id: string,
    data: {
      name?: string
      summaryPrompt?: string
      llmsTxtHeader?: string
      assembleTemplate?: string
      params?: Record<string, unknown>
      version?: number
    },
  ): Promise<PromptProfile> {
    return prisma.promptProfile.update({
      where: { id },
      data: {
        name: data.name,
        summary_prompt: data.summaryPrompt,
        llms_txt_header: data.llmsTxtHeader,
        assemble_template: data.assembleTemplate,
        params: data.params as Prisma.InputJsonValue,
        version: data.version,
      },
    })
  },

  /**
   * Delete prompt profile (if not in use)
   */
  async delete(id: string): Promise<void> {
    // Check if any domains are using this profile
    const domainsUsingProfile = await prisma.domain.count({
      where: { prompt_profile_id: id },
    })

    if (domainsUsingProfile > 0) {
      throw new Error(
        `Cannot delete prompt profile: ${domainsUsingProfile} domains are using it`,
      )
    }

    await prisma.promptProfile.delete({
      where: { id },
    })
  },

  /**
   * Clone a prompt profile with a new version
   */
  async clone(
    id: string,
    updates?: {
      name?: string
      summaryPrompt?: string
      llmsTxtHeader?: string
      assembleTemplate?: string
      params?: Record<string, unknown>
    },
  ): Promise<PromptProfile> {
    const original = await this.getById(id)
    if (!original) {
      throw new Error("Prompt profile not found")
    }

    return this.create({
      name: updates?.name ?? `${original.name} (v${original.version + 1})`,
      summaryPrompt: updates?.summaryPrompt ?? original.summary_prompt,
      llmsTxtHeader:
        updates?.llmsTxtHeader ?? original.llms_txt_header ?? undefined,
      assembleTemplate:
        updates?.assembleTemplate ?? original.assemble_template ?? undefined,
      params: updates?.params ?? (original.params as Record<string, unknown>),
      version: original.version + 1,
    })
  },

  /**
   * Get default prompt profile
   */
  async getDefault(): Promise<PromptProfile> {
    const existing = await prisma.promptProfile.findFirst({
      where: { name: "Default" },
    })

    if (existing) {
      return existing
    }

    // Create a default profile if it doesn't exist
    return this.create({
      name: "Default",
      summaryPrompt: `You are creating a comprehensive documentation file for Large Language Models (LLMs) to understand a website's structure, purpose, and content.

Analyze the provided website content and create a detailed summary that includes:
1. The main purpose and functionality of the website
2. Key features and capabilities
3. Important information architecture and navigation structure
4. Notable content sections or areas
5. Any technical details that would help an LLM understand how to interact with or reference this site

Be thorough but concise. Focus on information that would be most valuable for an LLM to understand the website's context and content.`,
      llmsTxtHeader: `# LLMs.txt - AI-Readable Website Documentation

This file contains structured information about the website to help Large Language Models understand its content, structure, and purpose.

Generated: {{date}}
Domain: {{domain}}

---

`,
      assembleTemplate: `{{header}}

## Website Overview

{{domainSummary}}

## Page Summaries

{{pageSummaries}}

---

Generated by llms-txt-generator
`,
      params: {
        similarityThreshold: 0.85,
        minContentLength: 100,
        maxSummaryLength: 500,
        includeMetadata: true,
      },
    })
  },
}
